apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: honeycomb-app-namespace-api-key
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: honeycomb-app-namespace-api-key
  data:
    - secretKey: HONEYCOMB_API_KEY
      remoteRef:
        key: honeycomb_app-namespace-api-key
