apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prefect-api-key
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: prefect-api-key
  data:
    - secretKey: key
      remoteRef:
        key: prefect_api-key
